name = "write-lean"
version = "0.1.0"
defaultTargets = ["write-lean"]

[[lean_lib]]
name = "WriteLean"

[[lean_exe]]
name = "write-lean"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.16.0"
